In [1]:
dataset  = [
    'I like cats',
    'I hate dogs',
    'I\'m impartial to hippos']

In [2]:
dataset[0]

'I like cats'

In [3]:
## Import Libraries


In [4]:
!pip install torchtext
!pip install nltk
!pip install spacy
!python -m spacy download en_core_web_sm
!pip install torch==2.2.2
!pip install torchtext==0.17.2
!pip install numpy==1.26.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 1.5 MB/s eta 0:00:0000:0100:01m
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [5]:
!pip install transformers

In [6]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

import spacy
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.util import ngrams
from transformers import BertTokenizer
from transformers import XLNetTokenizer


from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

def warn(*args,**kwargs):
    pass
import warnings
warnings.warn=warn
warnings.filterwarnings('ignore')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/tinonturjamajumder/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/tinonturjamajumder/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [7]:
import spacy

In [8]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

In [9]:
token = get_tokenizer('spacy',language = 'en_core_web_sm')


# Tokenize the sentence
def tokenize(iter_corpus,token):
    for sample in iter_corpus:
        
        yield token(sample)

corpus = iter(dataset)

# build the vocabulary from the token
vocab = build_vocab_from_iterator(map(token,corpus))
        

In [10]:
vocab.get_itos()

['I', "'m", 'cats', 'dogs', 'hate', 'hippos', 'impartial', 'like', 'to']

In [11]:
vocab.get_stoi()

{'impartial': 6,
 'hippos': 5,
 'to': 8,
 'hate': 4,
 'dogs': 3,
 "'m": 1,
 'like': 7,
 'cats': 2,
 'I': 0}

In [12]:
corpus_token = tokenize((iter(dataset)),token)

In [13]:
for text in corpus_token:
    print(text)

['I', 'like', 'cats']
['I', 'hate', 'dogs']
['I', "'m", 'impartial', 'to', 'hippos']


In [14]:
first_data = next(iter(dataset))
first_data

'I like cats'

In [17]:
import torch

In [19]:
input_ids = lambda x:[torch.tensor(vocab(token(data_sample))) for data_sample in dataset]

index = input_ids(dataset)
print(index)

[tensor([0, 7, 2]), tensor([0, 4, 3]), tensor([0, 1, 6, 8, 5])]


In [23]:
import torch.nn as nn
embedding_dim = 3
n_embedding = len(vocab) # --> 9


embeds = nn.Embedding(n_embedding,embedding_dim)
 
# output embedding --> (9,3)

In [21]:
n_embedding = len(vocab)
n_embedding

9

In [24]:
i_like_cats = embeds(index[0])
i_like_cats

tensor([[ 0.8126, -0.4158, -0.3561],
        [-0.1133, -0.8343, -1.5174],
        [-1.1168, -0.9135, -0.7031]], grad_fn=<EmbeddingBackward0>)

In [24]:
conda install numpy h5py --force-reinstall


Channels:
 - defaults
Platform: osx-arm64
doneecting package metadata (repodata.json): - 
doneing environment: / 

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - h5py
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    h5py-3.12.1                |  py312h0957e0b_1         1.3 MB
    hdf5-1.14.5                |       hd77251f_2         5.6 MB
    pytables-3.10.2            |  py312h396ba24_1         1.7 MB
    ------------------------------------------------------------
                                           Total:         8.6 MB

The following packages will be UPDATED:

  h5py                               3.11.0-py312haac6407_0 --> 3.12.1-py312h0957e0b_1 
  hdf5                                    1.12.1-h05c076b_3 --> 1.14.5-hd77251f_2 
  pytables                           3.10.1-py312h905a39b_0 --> 3.10.2-py312h396ba24_1 



hd

In [26]:
import numpy
print(numpy.__version__)


2.2.5


In [27]:
!pip install numpy==1.26.0

In [28]:
numpy.__version__

'2.2.5'

In [3]:
!pip install torch==2.2.2 torchtext==0.17.2 numpy==1.26.0 h5py==3.10.0 spacy==3.7.2 nltk
!python -m spacy download en_core_web_sm


  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl (12.8 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [25]:
dataset_2 = ["Reality is often harsh",
             "if you want to get sucess in life you have to come out from your comfort zone",
             "I don't loose"]

        

In [29]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

tokenizer = get_tokenizer(tokenizer = 'spacy', language = 'en_core_web_sm')

vocab = build_vocab_from_iterator(map(tokenizer,dataset_2))

In [31]:
vocab.get_stoi()

{'sucess': 19,
 'out': 18,
 'often': 17,
 'loose': 15,
 'life': 14,
 'in': 12,
 'want': 20,
 'is': 13,
 'have': 10,
 'get': 8,
 'do': 6,
 'your': 21,
 'harsh': 9,
 'comfort': 5,
 'zone': 22,
 'come': 4,
 'I': 2,
 'if': 11,
 'from': 7,
 "n't": 16,
 'you': 1,
 'Reality': 3,
 'to': 0}

In [36]:
input_idx = lambda x:[torch.tensor(vocab(tokenizer(data_sample))) for data_sample in dataset_2]
in_idx = input_idx(dataset_2)

In [37]:
in_idx

[tensor([ 3, 13, 17,  9]),
 tensor([11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7, 21,  5, 22]),
 tensor([ 2,  6, 16, 15])]

In [54]:
# The previous method

from torch.utils.data import Dataset,DataLoader
# Create custom dataset
class CustomDataset(Dataset):

    def __init__(self,corpus,tokenizer,vocab):

        self.corpus = corpus
        self.tokenizer = tokenizer
        self.vocab = vocab


    def __len__(self):
        return len(self.corpus)


    def __getitem__(self,idx):
        tokens = self.tokenizer(self.corpus[idx])

        token_indices = [self.vocab[token] for token in tokens]

        return torch.tensor(token_indices)
    

    

In [71]:
tokenizer = get_tokenizer('spacy',language = 'en_core_web_sm')

vocab = build_vocab_from_iterator(map(tokenizer, dataset_2))

cust_data = CustomDataset(corpus = dataset_2,
                          tokenizer = tokenizer, 
                          vocab = vocab)


In [60]:
for i in range(len(dataset_2)):
    value = cust_data[i]
    print(value)

tensor([ 3, 13, 17,  9])
tensor([11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7, 21,  5, 22])
tensor([ 2,  6, 16, 15])


In [62]:
data_3 = ['Ting Tong',
          'Ping Pong',
          'Ching Chong']



In [63]:
tokenizer = get_tokenizer('spacy',language = 'en_core_web_sm')

vocab = build_vocab_from_iterator(map(tokenizer, data_3))

cust_data = CustomDataset(corpus = data_3,
                          tokenizer = tokenizer, 
                          vocab = vocab)


In [64]:
for i in range(len(data_3)):
    value = cust_data[i]
    print(value)

tensor([4, 5])
tensor([2, 3])
tensor([0, 1])


In [65]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    padded_batch = pad_sequence(batch,batch_first = True, padding_value=0)

    return padded_batch
    

    
    

In [74]:
from torch.utils.data import DataLoader

custom_collate_dataloader = DataLoader(dataset = cust_data,
                                       batch_size = 2,
                                       collate_fn = collate_fn)
                                       

In [75]:
for batch in custom_collate_dataloader:
    print(batch)

tensor([[ 3, 13, 17,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7, 21,  5, 22]])
tensor([[ 2,  6, 16, 15]])
