In [2]:
dataset  = [
    'I like cats',
    'I hate dogs',
    'I\'m impartial to hippos']

In [3]:
dataset[0]

'I like cats'

In [4]:
## Import Libraries


In [5]:
!pip install torchtext
!pip install nltk
!pip install spacy
!python -m spacy download en_core_web_sm
!pip install torch==2.2.2
!pip install torchtext==0.17.2
!pip install numpy==1.26.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 2.8 MB/s eta 0:00:00a 0:00:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [6]:
!pip install transformers

In [7]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

import spacy
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.util import ngrams
from transformers import BertTokenizer
from transformers import XLNetTokenizer


from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

def warn(*args,**kwargs):
    pass
import warnings
warnings.warn=warn
warnings.filterwarnings('ignore')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/tinonturjamajumder/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/tinonturjamajumder/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [8]:
import spacy

In [9]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

In [10]:
token = get_tokenizer('spacy',language = 'en_core_web_sm')


# Tokenize the sentence
def tokenize(iter_corpus,token):
    for sample in iter_corpus:
        
        yield token(sample)

corpus = iter(dataset)

# build the vocabulary from the token
vocab = build_vocab_from_iterator(map(token,corpus))
        

In [11]:
vocab.get_itos()

['I', "'m", 'cats', 'dogs', 'hate', 'hippos', 'impartial', 'like', 'to']

In [12]:
vocab.get_stoi()

{'impartial': 6,
 'hippos': 5,
 'to': 8,
 'hate': 4,
 'dogs': 3,
 "'m": 1,
 'like': 7,
 'cats': 2,
 'I': 0}

In [13]:
corpus_token = tokenize((iter(dataset)),token)

In [14]:
for text in corpus_token:
    print(text)

['I', 'like', 'cats']
['I', 'hate', 'dogs']
['I', "'m", 'impartial', 'to', 'hippos']


In [15]:
first_data = next(iter(dataset))
first_data

'I like cats'

In [16]:
import torch

In [17]:
input_ids = lambda x:[torch.tensor(vocab(token(data_sample))) for data_sample in dataset]

index = input_ids(dataset)
print(index)

[tensor([0, 7, 2]), tensor([0, 4, 3]), tensor([0, 1, 6, 8, 5])]


In [18]:
import torch.nn as nn
embedding_dim = 3
n_embedding = len(vocab) # --> 9


embeds = nn.Embedding(n_embedding,embedding_dim)
 
# output embedding --> (9,3)

In [19]:
n_embedding = len(vocab)
n_embedding

9

In [20]:
i_like_cats = embeds(index[0])
i_like_cats

tensor([[ 1.1146, -0.4186, -0.6799],
        [ 1.3324, -1.2267, -0.2111],
        [-0.7752,  0.5660,  1.7723]], grad_fn=<EmbeddingBackward0>)

In [21]:
conda install numpy h5py --force-reinstall


Channels:
 - defaults
Platform: osx-arm64
doneecting package metadata (repodata.json): - 
doneing environment: | 

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - h5py
    - numpy





donearing transaction: - 
donefying transaction: | 
doneuting transaction: - 

Note: you may need to restart the kernel to use updated packages.


In [22]:
import numpy
print(numpy.__version__)


1.26.0


In [23]:
!pip install numpy==1.26.0

In [24]:
numpy.__version__

'1.26.0'

In [25]:
!pip install torch==2.2.2 torchtext==0.17.2 numpy==1.26.0 h5py==3.10.0 spacy==3.7.2 nltk
!python -m spacy download en_core_web_sm


  Using cached h5py-3.10.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.5 kB)
Using cached h5py-3.10.0-cp312-cp312-macosx_11_0_arm64.whl (2.6 MB)
  Attempting uninstall: h5py
    Found existing installation: h5py 3.12.1
    Uninstalling h5py-3.12.1:
      Successfully uninstalled h5py-3.12.1
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl (12.8 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [26]:
dataset_2 = ["Reality is often harsh",
             "if you want to get sucess in life you have to come out from your comfort zone",
             "I don't loose"]

        

In [27]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

tokenizer = get_tokenizer(tokenizer = 'spacy', language = 'en_core_web_sm')

vocab = build_vocab_from_iterator(map(tokenizer,dataset_2))

In [28]:
vocab.get_stoi()

{'sucess': 19,
 'out': 18,
 'often': 17,
 'loose': 15,
 'life': 14,
 'in': 12,
 'want': 20,
 'is': 13,
 'have': 10,
 'get': 8,
 'do': 6,
 'your': 21,
 'harsh': 9,
 'comfort': 5,
 'zone': 22,
 'come': 4,
 'I': 2,
 'if': 11,
 'from': 7,
 "n't": 16,
 'you': 1,
 'Reality': 3,
 'to': 0}

In [29]:
input_idx = lambda x:[torch.tensor(vocab(tokenizer(data_sample))) for data_sample in dataset_2]
in_idx = input_idx(dataset_2)

In [30]:
in_idx

[tensor([ 3, 13, 17,  9]),
 tensor([11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7, 21,  5, 22]),
 tensor([ 2,  6, 16, 15])]

In [31]:
# The previous method

from torch.utils.data import Dataset,DataLoader
# Create custom dataset
class CustomDataset(Dataset):

    def __init__(self,corpus,tokenizer,vocab):

        self.corpus = corpus
        self.tokenizer = tokenizer
        self.vocab = vocab


    def __len__(self):
        return len(self.corpus)


    def __getitem__(self,idx):
        tokens = self.tokenizer(self.corpus[idx])

        token_indices = [self.vocab[token] for token in tokens]

        return torch.tensor(token_indices)
    

    

In [32]:
tokenizer = get_tokenizer('spacy',language = 'en_core_web_sm')

vocab = build_vocab_from_iterator(map(tokenizer, dataset_2))

cust_data = CustomDataset(corpus = dataset_2,
                          tokenizer = tokenizer, 
                          vocab = vocab)


In [33]:
for i in range(len(dataset_2)):
    value = cust_data[i]
    print(value)

tensor([ 3, 13, 17,  9])
tensor([11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7, 21,  5, 22])
tensor([ 2,  6, 16, 15])


In [34]:
data_3 = ['Ting Tong',
          'Ping Pong',
          'Ching Chong']



In [35]:
tokenizer = get_tokenizer('spacy',language = 'en_core_web_sm')

vocab = build_vocab_from_iterator(map(tokenizer, data_3))

cust_data = CustomDataset(corpus = data_3,
                          tokenizer = tokenizer, 
                          vocab = vocab)


In [36]:
for i in range(len(data_3)):
    value = cust_data[i]
    print(value)

tensor([4, 5])
tensor([2, 3])
tensor([0, 1])


In [37]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    padded_batch = pad_sequence(batch,batch_first = True, padding_value=0)

    return padded_batch
    

    
    

In [38]:
from torch.utils.data import DataLoader

custom_collate_dataloader = DataLoader(dataset = cust_data,
                                       batch_size = 2,
                                       collate_fn = collate_fn)
                                       

In [39]:
for batch in custom_collate_dataloader:
    print(batch)

tensor([[4, 5],
        [2, 3]])
tensor([[0, 1]])


In [40]:
dataset_2

['Reality is often harsh',
 'if you want to get sucess in life you have to come out from your comfort zone',
 "I don't loose"]

In [41]:
tokenizer = get_tokenizer('spacy','en_core_web_sm')
vocab = build_vocab_from_iterator(map(tokenizer,dataset_2))



In [42]:
input_ids = lambda x:[torch.tensor(vocab(tokenizer(data_sample))) for data_sample in dataset_2]

indx = input_ids(dataset_2)

print(indx)

[tensor([ 3, 13, 17,  9]), tensor([11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7, 21,  5, 22]), tensor([ 2,  6, 16, 15])]


In [43]:
embedding_dim = 3

n_embedding = len(vocab)

embeds = nn.Embedding(n_embedding,embedding_dim)

In [44]:
# Pass the index of the strings and get the embeddings value
reality_is_often_harsh = embeds(indx[0])
reality_is_often_harsh

tensor([[-0.2157, -0.5888,  1.9749],
        [-0.7098, -0.7384, -0.4656],
        [-0.7088,  0.8017, -0.8783],
        [ 0.5905, -0.3603,  0.6245]], grad_fn=<EmbeddingBackward0>)

In [45]:
## Embedding_Bag

embedding_bag = nn.EmbeddingBag(n_embedding,embedding_dim) # --> col x row

dataset_2 = ['Reality is often harsh','if you want to get sucess in life you have to come out from your comfort zone',"I don't loose"]

# index:[tensor([ 3, 13, 17,  9]), tensor([11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7, 21,  5, 22]), tensor([ 2,  6, 16, 15])]

reality_is_often_harsh = embedding_bag(index[0],offsets = torch.tensor([0]))

reality_is_often_harsh

tensor([[0.6257, 0.9233, 0.4653]], grad_fn=<EmbeddingBagBackward0>)

In [46]:
i_don_lose_embeds = embeds(indx[-1])
i_don_lose_embed_bags = embedding_bag(indx[-1],offsets = torch.tensor([0]))
i_don_lose_embeds,i_don_lose_embed_bags


(tensor([[-0.7283, -0.7614, -2.2720],
         [-1.5604,  0.6884, -0.7873],
         [-0.5793, -1.7749,  0.1555],
         [-0.5719, -0.2992,  0.9742]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.4068, -0.7567, -0.5539]], grad_fn=<EmbeddingBagBackward0>))

In [47]:
sen_2 = embeds(indx[1])
sen_2_bag = embedding_bag(indx[1],offsets = torch.tensor([0]))
sen_2,sen_2_bag

(tensor([[ 1.5142,  0.3452,  2.0134],
         [ 2.1682,  0.2330, -0.3678],
         [ 1.2203, -0.7026,  0.5975],
         [-0.8872,  0.0449,  0.0941],
         [-0.6736,  0.0433, -0.0377],
         [ 1.6218, -1.1653, -0.1014],
         [ 0.7102, -0.2121, -0.6422],
         [-1.9016, -0.7593,  0.6662],
         [ 2.1682,  0.2330, -0.3678],
         [ 1.1286, -0.4780, -1.0295],
         [-0.8872,  0.0449,  0.0941],
         [ 0.9534,  0.7460, -1.9702],
         [ 0.7290,  2.0171,  0.5251],
         [ 0.6290,  0.7268, -1.6474],
         [ 0.5615,  0.3190, -0.1727],
         [-0.0881, -1.6550, -0.7782],
         [ 1.3964,  1.0529, -1.3251]], grad_fn=<EmbeddingBackward0>),
 tensor([[0.1973, 0.5154, 0.0156]], grad_fn=<EmbeddingBagBackward0>))

In [48]:
index_flat = torch.cat(indx)
index_flat

tensor([ 3, 13, 17,  9, 11,  1, 20,  0,  8, 19, 12, 14,  1, 10,  0,  4, 18,  7,
        21,  5, 22,  2,  6, 16, 15])

## Offset

In NLP datasets are often represented as one dimensional tensors. However, when working with embedding bags and other applications, it's crucial to identify the position of each document. Let's dive into this with our sample dataset. You combine the tensors of individual documents using the Cat function with the index setting. The *`offset parameter`* captures the *`starting position`* of every document. 

In [49]:
offset = [len(sample) for sample in indx]
offset.insert(0,0)
offset = torch.cumsum(torch.tensor(offset),dim = 0)[0:-1]
offset

tensor([ 0,  4, 21])

In [ ]:
my_embedding_bag = embedding_bag(index_flat,offsets = offset)