In [1]:
import torch
import torch.nn as nn
import torchtext


In [2]:
embedding_dim = 3
context_size = 2
vocab = 4

embedding = nn.Embedding(vocab,embedding_dim)
linear = nn.Linear(context_size*embedding_dim,2)

In [4]:
inputs = torch.tensor([2,3])

my_embeddings = embedding(inputs)


In [5]:
my_embeddings

tensor([[-1.2908,  0.1873,  0.6990],
        [-0.4541,  0.0991, -0.4244]], grad_fn=<EmbeddingBackward0>)

In [9]:
my_embeddings_c = torch.reshape(my_embeddings,
                                (-1,context_size*embedding_dim))

# -1 indicates pytorch to infer the appropriate size for that dimension based on the other dimensions and the total number of elements
linear1 = linear(my_embeddings_c)
linear1

tensor([[ 0.4941, -0.1846]], grad_fn=<AddmmBackward0>)

In [8]:
my_embeddings_c

tensor([[-1.2908,  0.1873,  0.6990, -0.4541,  0.0991, -0.4244]],
       grad_fn=<ViewBackward0>)