In [1]:
rhyme_collection = """A is for apple, red and sweet.
B is for ball bounce to the beat.
C is for cat who likes to play.
Learn your letters every day.

D is for dog bark and run.
E is for elephant having fun.
F is for fish swimming in the sea
Learn all the letters you see.

G is for goats eating grass.
H is for horse running fast.
I is for igloo in the snow.
So many letters, you know.

J is for jump, let’s move around.
K is for kite flying with no sound.
L is for lion, king of the land.
Learning letters hand in hand.

M is for monkey swinging in a tree.
N is for nest where birds like to be.
O is for ocean deep and blue.
Home to whales and dolphins too.

P is for panda eating bamboo.
Q is for Queen waving at you.
R is for rabbit hopping so fast.
Learning letters is a blast.

S is for snake sliding by.
T is for tiger roar, oh my.
U for umbrella, it keeps us dry.
It’s fun, give it a try.

V for violin playing a tune.
W is for whale under the moon.
X is for xylophone playing a song.
Come on, sing along.

Y is for yank big and strong.
Z for zebra stripes so long.
Now we know our ABCs,
So please sing with me.

Let’s sing the alphabet.
This is fun, we won’t forget.
From A-Z we know them all.
Letters big and letters small.

A-hunting we will go,
A-hunting we will go,
Heigh-ho, the derry-o,
A-hunting we will go.

A-hunting we will go,
A-hunting we will go,
We’ll catch a fox and put him in a box,
And then we’ll let him go!

A-hunting we will go,
A-hunting we will go,
We’ll catch a fish and put it on a dish,
And then we’ll let it go!

A-hunting we will go,
A-hunting we will go,
We’ll catch a bear and put him in a chair,
And then we’ll let him go!

A-hunting we will go,
A-hunting we will go,
We’ll catch a goat and put him on a boat,
And then we’ll let him go!

A-hunting we will go,
A-hunting we will go,
We’ll catch a cat and put him in a hat,
And then we’ll let him go!

A-hunting we will go,
A-hunting we will go,
We’ll catch a snake and put him on a cake,
And then we’ll let him go!

A-hunting we will go,
A-hunting we will go,
We’ll catch a duck and put him in a truck,
And then we’ll let him go!

Baby Shark
Doo doo doo doo doo doo
Baby shark, doo doo doo doo doo doo
Baby shark, doo doo doo doo doo doo
Baby shark!

Mommy Shark
Doo doo doo doo doo doo
Mommy shark, doo doo doo doo doo doo
Mommy shark, doo doo doo doo doo doo
Mommy shark!

Daddy Shark
Doo doo doo doo doo doo
Daddy shark, doo doo doo doo doo doo
Daddy shark, doo doo doo doo doo doo
Daddy shark!

Grandma Shark
Doo doo doo doo doo doo
Grandma shark, doo doo doo doo doo doo
Grandma shark, doo doo doo doo doo doo
Grandma shark!

Grandpa Shark
Doo doo doo doo doo doo
Grandpa shark, doo doo doo doo doo doo
Grandpa shark, doo doo doo doo doo doo
Grandpa shark!

Let’s Go Hunt
Doo doo doo doo doo doo
Let’s go hunt, doo doo doo doo doo doo
Let’s go hunt, doo doo doo doo doo doo
Let’s go hunt!

Run Away
Doo doo doo doo doo doo
Run away, doo doo doo doo doo doo
Run away, doo doo doo doo doo doo
Run away!

Safe at Last
Doo doo doo doo doo doo
Safe at last, doo doo doo doo doo doo
Safe at last, doo doo doo doo doo doo
Safe at last!

It’s the End
Doo doo doo doo doo doo
It’s the end, doo doo doo doo doo doo
It’s the end, doo doo doo doo doo doo
It’s the end!

Head, shoulders, knees, and toes, knees and toes
Head, shoulders, knees, and toes, knees and toes
And eyes and ears and mouth and nose
Head, shoulders, knees, and toes, knees and toes

Head, shoulders, knees, and toes, knees and toes
Head, shoulders, knees, and toes, knees and toes
And eyes and ears and mouth and nose
Head, shoulders, knees, and toes, knees and toes

A B C D E F G
H I J K L M N O P
Q R S T U V
W X Y and Z

Now I know my ABCs
Next time won’t you sing with me?

Five little penguins went out one day,
Over the iceberg and far away,
Mother duck said, “Waddle, waddle, waddle”,
But only four came back to cuddle.
Four little penguins went out one day,
Over the iceberg and far away,
Mother duck said, “Waddle, waddle, waddle”,
But only three came back to cuddle.

Three little penguins went out one day,
Over the iceberg and far away,
Mother duck said, “Waddle, waddle, waddle”,
But only two came back to cuddle.

Two little penguins went out one day,
Over the iceberg and far away,
Mother duck said, “Waddle, waddle, waddle”,
But only one came back to cuddle.

One little penguins went out one day,
Over the iceberg and far away,
Mother duck said, “Waddle, waddle, waddle”,
But none of them came back to cuddle.

Sad mother penguin went out one day,
Calling her children “Come this way”,
Mother duck said, “Waddle, waddle, waddle”,
And all five came back to cuddle.

Five little penguins went out one day,
Over the iceberg and far away,
Mother duck said, “Waddle, waddle, waddle”,
And all five came back to cuddle.

This is the way we wash our face,
Wash our face, wash our face,
This is the way we wash our face,
So early in the morning.
This is the way we brush our teeth,
Brush our teeth, brush our teeth,
This is the way we brush our teeth,
So early in the morning.

This is the way we comb our hair,
Comb our hair, comb our hair,
This is the way we comb our hair,
So early in the morning.

This is the way we put on clothes,
Put on clothes, put on clothes,
This is the way we put on clothes,
So early in the morning.

This is the way we eat our food,
Eat our food, eat our food,
This is the way we eat our food,
Before we go to school.

This is the way we go to school,
Go to school, go to school,
This is the way we go to school,
To learn and have some fun!

Mary had a little lamb,
Its fleece was white as snow,
And everywhere that Mary went,
The lamb was sure to go.
It followed her to school one day,
Which was against the rule,
It made the children laugh and play,
To see a lamb at school.

And so the teacher turned it out,
But still it lingered near,
And waited patiently about,
Till Mary did appear.

“Why does the lamb love Mary so?”
The eager children cry.
“Why, Mary loves the lamb, you know,”
The teacher did reply.

Row, row, row your boat,
Gently down the stream.
Merrily, merrily, merrily, merrily,
Life is but a dream.
Row, row, row your boat,
Gently down the stream.
If you see a crocodile,
Don’t forget to scream.

Row, row, row your boat,
Gently down the river.
If you see a polar bear,
Don’t forget to shiver.

Row, row, row your boat,
Gently down the creek.
If you see a little mouse,
Don’t forget to squeak.

Row, row, row your boat,
Gently to the shore.
If you see a lion,
Don’t forget to roar.

The itsy bitsy spider climbed up the water spout.
Down came the rain and washed the spider out.
Out came the sun and dried up all the rain,
And the itsy bitsy spider climbed up the spout again.

Old MacDonald had a farm, E-I-E-I-O,
And on his farm he had some cows, E-I-E-I-O,
With a moo-moo here, And a moo-moo there,
Here a moo, there a moo, Everywhere a moo-moo,
Old MacDonald had a farm, E-I-E-I-O.
Old MacDonald had a farm, E-I-E-I-O,
And on his farm he had some chicks, E-I-E-I-O,
With a cluck-cluck here, And a cluck-cluck there,
Here a cluck, there a cluck, Everywhere a cluck-cluck,
Old MacDonald had a farm, E-I-E-I-O.

Old MacDonald had a farm, E-I-E-I-O,
And on his farm he had some pigs, E-I-E-I-O,
With an oink-oink here, And an oink-oink there,
Here an oink, there an oink, Everywhere an oink-oink,
Old MacDonald had a farm, E-I-E-I-O.

Old MacDonald had a farm, E-I-E-I-O,
And on his farm he had some sheep, E-I-E-I-O,
With a baa-baa here, And a baa-baa there,
Here a baa, there a baa, Everywhere a baa-baa,
Old MacDonald had a farm, E-I-E-I-O.

Old MacDonald had a farm, E-I-E-I-O,
And on his farm he had some horses, E-I-E-I-O,
With a neigh-neigh here, And a neigh-neigh there,
Here a neigh, there a neigh, Everywhere a neigh-neigh,
Old MacDonald had a farm, E-I-E-I-O.

The wheels on the bus go round and round,
Round and round, round and round,
The wheels on the bus go round and round,
All through the town.
The wipers on the bus go swish, swish, swish,
Swish, swish, swish, swish, swish, swish,
The wipers on the bus go swish, swish, swish,
All through the town.

The horn on the bus goes beep, beep, beep,
Beep, beep, beep, beep, beep, beep,
The horn on the bus goes beep, beep, beep,
All through the town.

The doors on the bus go open and shut,
Open and shut, open and shut,
The doors on the bus go open and shut,
All through the town.

The driver on the bus says “Move on back,
Move on back, move on back,”
The driver on the bus says “Move on back,”
All through the town.

The babies on the bus go “Wah, wah, wah!
Wah, wah, wah, wah, wah, wah!”
The babies on the bus go “Wah, wah, wah!”
All through the town.

The parents on the bus say “Shh, shh, shh,
Shh, shh, shh, shh, shh, shh,”
The parents on the bus say “Shh, shh, shh,”
All through the town.

The people on the bus go up and down,
Up and down, up and down.
The people on the bus go up and down,
All through the town.

London Bridge is falling down,
Falling down, falling down,
London Bridge is falling down,
My fair lady.
Build it up with wood and clay,
Wood and clay, wood and clay,
Build it up with wood and clay,
My fair lady.

Wood and clay will wash away,
Wash away, wash away,
Wood and clay will wash away,
My fair lady.

Build it up with bricks and mortar,
Bricks and mortar, bricks and mortar,
Build it up with bricks and mortar,
My fair lady.

Bricks and mortar will not stay,
Will not stay, will not stay,
Bricks and mortar will not stay,
My fair lady.

Build it up with iron and steel,
Iron and steel, iron and steel,
Build it up with iron and steel,
My fair lady.

Iron and steel will bend and bow,
Bend and bow, bend and bow,
Iron and steel will bend and bow,
My fair lady.

Build it up with silver and gold,
Silver and gold, silver and gold,
Build it up with silver and gold,
My fair lady.

Silver and gold will be stolen away,
Stolen away, stolen away,
Silver and gold will be stolen away,
My fair lady.

Set a man to watch all night,
Watch all night, watch all night,
Set a man to watch all night,
My fair lady.

Suppose the man should fall asleep,
Fall asleep, fall asleep,
Suppose the man should fall asleep?
My fair lady.

Take the key and lock him up,
Lock him up, lock him up,
Take the key and lock him up,
My fair lady.

Ring-a-ring o’ roses,
A pocket full of posies,
A-tishoo! A-tishoo!
We all fall down.
Cows are in the meadow,
Eating buttercups,
A-tishoo! A-tishoo!
We all jump up.

Fish are in the water,
Fish are in the sea,
We all jump up,
With a one, two, three.

The king has sent his daughter,
To fetch a pail of water,
A-tishoo! A-tishoo!
We all fall down.

The bird upon the steeple,
Sits high above the people,
A-tishoo! A-tishoo!
We all fall down.

The wedding bells are ringing,
The boys and girls are singing,
A-tishoo! A-tishoo!
We all fall down.

The American version is sometimes called “Ring Around a Rosie” and it goes:

Ring around the rosie,
Pocket full of posies,
Ashes, ashes,
We all fall down!

Five little ducks went out one day,
Over the hill and far away,
Mother duck said, “Quack, quack, quack, quack”,
But only four little ducks came back.
Four little ducks went out one day,
Over the hill and far away,
Mother duck said, “Quack, quack, quack, quack”,
But only three little ducks came back.

Three little ducks went out one day,
Over the hill and far away,
Mother duck said, “Quack, quack, quack, quack”,
But only two little ducks came back.

Two little ducks went out one day,
Over the hill and far away,
Mother duck said, “Quack, quack, quack, quack”,
But only one little duck came back.

One little duck went out one day,
Over the hill and far away
The little duck said, “Quack, quack, quack, quack”
And then no more little ducks came back.

Sad mother duck went out one day,
Over the hill and far away
The little duck said, “Quack, quack, quack, quack”
And all five little ducks came back.

Five little ducks went out one day,
Over the hill and far away,
Mother duck said, “Quack, quack, quack, quack”,
All five little ducks came back.

If you’re happy and you know it, clap your hands (clap clap)
If you’re happy and you know it, clap your hands (clap clap)
If you’re happy and you know it, then your face will surely show it
If you’re happy and you know it, clap your hands. (clap clap)
If you’re happy and you know it, stomp your feet (stomp stomp)
If you’re happy and you know it, stomp your feet (stomp stomp)
If you’re happy and you know it, then your face will surely show it
If you’re happy and you know it, stomp your feet. (stomp stomp)

If you’re happy and you know it, shout “Hooray!” (hooray!)
If you’re happy and you know it, shout “Hooray!” (hooray!)
If you’re happy and you know it, then your face will surely show it
If you’re happy and you know it, shout “Hooray!” (hooray!)

If you’re happy and you know it, do all three (clap clap, stomp stomp, hooray!)
If you’re happy and you know it, do all three (clap clap, stomp stomp, hooray!)
If you’re happy and you know it, then your face will surely show it
If you’re happy and you know it, do all three. (clap clap, stomp stomp, hooray!)

The farmer in the dell,
The farmer in the dell,
Heigh-ho, the derry-o,
The farmer in the dell.
The farmer takes a wife,
The farmer takes a wife,
Heigh-ho, the derry-o,
The farmer takes a wife.

The wife takes a child,
The wife takes a child,
Heigh-ho, the derry-o,
The wife takes a child.

The child takes a nurse,
The child takes a nurse,
Heigh-ho, the derry-o,
The child takes a nurse.

The nurse takes a cow,
The nurse takes a cow,
Heigh-ho, the derry-o,
The nurse takes a cow.

The cow takes a dog,
The cow takes a dog,
Heigh-ho, the derry-o,
The cow takes a dog.

The dog takes a cat,
The dog takes a cat,
Heigh-ho, the derry-o,
The dog takes a cat.

The cat takes a rat,
The cat takes a rat,
Heigh-ho, the derry-o,
The cat takes a rat.

The rat takes the cheese,
The rat takes the cheese,
Heigh-ho, the derry-o,
The rat takes the cheese.

The cheese stands alone,
The cheese stands alone,
Heigh-ho, the derry-o,
The cheese stands alone.

This old man, he played one,
He played knick-knack on my thumb,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.
This old man, he played two,
He played knick-knack on my shoe,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played three,
He played knick-knack on my knee,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played four,
He played knick-knack on my door,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played five,
He played knick-knack on my hive,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played six,
He played knick-knack on my sticks,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played seven,
He played knick-knack up in heaven,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played eight,
He played knick-knack on my gate,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played nine,
He played knick-knack on my spine,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

This old man, he played ten,
He played knick-knack once again,
With a knick-knack, paddywhack, give the dog a bone,
This old man came rolling home.

Hey diddle diddle,
The cat and the fiddle,
The cow jumped over the moon.
The little dog laughed to see such sport,
And the dish ran away with the spoon."""

## Importing Libraries

In [2]:
import re
import string
import os
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
from torch.utils.data import Dataset,DataLoader
import torch.nn as nn
import torch.nn.functional as F

import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator


import warnings
def warn(*args,**kwargs):
    pass

warnings.warn = warn

## Process Tokens

In [3]:
def preprocess_string(s):
    """
    Removes anything apart from letters(a-z & A-Z) from the inputs

    Paramters:
        s: (string)--> words combined with letters, numbers and signs

    Returns:
        s: (string) --> returns words consists of only digits
        
    """
    # Removes anything aparts from words, including signs and space
    s = re.sub(r"[^\w\s]",'',s)

    # Removes one or more white space
    s = re.sub(r"\s+",'',s)

    # Removes digits from the string
    s = re.sub(r"\d",'',s)

    return s

## Token and Vocabulary

In [4]:
tokenizer = get_tokenizer('basic_english')

In [5]:
def tokenized_process_word(word):

    """
    Takes the whole dataset and converts it into smaller units/words/tokens.

    Parameters:
        word(string): whole dataset

    Returns:
        tokens
    """

    tokens = tokenizer(word)


    return [preprocess_string(w).lower() for w in tokens if len(w) !=0 and w not in string.punctuation]

In [6]:
# Check spell
tokens = tokenized_process_word(rhyme_collection)
tokens[:10]

['a', 'is', 'for', 'apple', 'red', 'and', 'sweet', 'b', 'is', 'for']

In [7]:
len(tokens)

3030

In [8]:
vocab = build_vocab_from_iterator(map(tokenizer,rhyme_collection.split()),specials = ["<unk>"])
vocab.set_default_index(vocab["<unk>"])


In [9]:
words = list(vocab.get_itos())[:10]
words


['<unk>', ',', 'the', 'doo', 'and', '.', 'a', 'go', 'is', 'on']

In [10]:
words_dict_keys = list(vocab.get_stoi().keys())[:10]
words_dict_values = list(vocab.get_stoi().values())[:10]
words_dict_keys,words_dict_values

(['zebra',
  'white',
  'which',
  'where',
  'washed',
  'us',
  'under',
  'umbrella',
  'turned',
  'tune'],
 [487, 483, 482, 481, 475, 471, 469, 468, 467, 466])

In [11]:
vocab['zebra']

487

## Create Embeddings

In [12]:
def genembeddings(vocab,embedding_dim = 20):

    """
    Turning words into dense vectors, which is fit for feeding into neutral network

    Parameters:
        vocab: (word_indices) --> indices of per tokens
        embedding_dim () --> feature values of per word.


    Returns:
        embedding: torch.nn.Embedding --> Returns a embedding vector of per tokens
    """

    vocab_size = len(vocab)
    embedding = nn.Embedding(vocab_size,embedding_dim)

    return embedding

In [13]:
embeds = genembeddings(vocab)
embeds

Embedding(490, 20)

In [14]:
embeds(torch.tensor(3))

tensor([ 0.6003, -0.6521, -0.2399,  1.3848, -0.3452, -2.0911, -0.4037, -0.9805,
        -0.2060, -0.7038, -0.8407,  0.1107,  0.4359, -0.4235, -0.5979, -1.8932,
         1.0299,  0.3605,  1.5663, -1.6636], grad_fn=<EmbeddingBackward0>)

## Context-Target Pair Formation

In [15]:
def genngrams(tokens,batch_size,context_size):

    """
    for n-gram model, model predict words based on previous words or contexts.

    Parameters:
        tokens:(words) --> full vocab should be set


    Returns:
        return a list of tuples, contains x = context and y = vocab
    """

    ngrams = [
        (
            [tokens[i-j-1] for j in range(context_size)],
            tokens[i]
        ) for i in range(context_size,batch_size)
    ]

    return ngrams

    

In [16]:
BATCH_SIZE = len(tokens)
CONTEXT_SIZE = 3

three_gram = genngrams(tokens = tokens,
                 batch_size = BATCH_SIZE,
                 context_size = CONTEXT_SIZE)

In [17]:
context_target_pair = three_gram[:10]
context_target_pair


[(['for', 'is', 'a'], 'apple'),
 (['apple', 'for', 'is'], 'red'),
 (['red', 'apple', 'for'], 'and'),
 (['and', 'red', 'apple'], 'sweet'),
 (['sweet', 'and', 'red'], 'b'),
 (['b', 'sweet', 'and'], 'is'),
 (['is', 'b', 'sweet'], 'for'),
 (['for', 'is', 'b'], 'ball'),
 (['ball', 'for', 'is'], 'bounce'),
 (['bounce', 'ball', 'for'], 'to')]

In [25]:
x,y = context_target_pair[0]
vocab(x)


[21, 8, 6]

## Creating Collate Function

In [33]:
CONTEXT_SIZE =3

def collate_fn(batch):
    """
    Custom collate function defines, represents how would the return file be after going through dataloader.
    collate function returns files according to the context size, depending on the context size, context embeddings, and target embeddings are sent to the ANN model

    Parameters:
        batch:(tokens) --> batch of tokens are feed
        context_size: (int) --> the number of samples neural network model will take as input at a time
        

    Returns:
        Tuple: --> torch.tensor(context_embeddings),torch.tensor(target_embeddings)
    
    """

    context,target = [],[]

    batch_size = len(batch)

    for i in range(CONTEXT_SIZE,batch_size):
        target.append(vocab[batch[i]])

        context.append(vocab([batch[i-j-1] for j in range(CONTEXT_SIZE)]))

    return torch.tensor(context),torch.tensor(target)

In [39]:
torch.manual_seed(42)
batch_size = 32

dataloader = DataLoader(dataset = tokens,batch_size = batch_size,shuffle = False, collate_fn=collate_fn)


In [40]:
context,target = next(iter(dataloader))
context,target

(tensor([[ 21,   8,   6],
         [313,  21,   8],
         [415, 313,  21],
         [  4, 415, 313],
         [453,   4, 415],
         [217, 453,   4],
         [  8, 217, 453],
         [ 21,   8, 217],
         [315,  21,   8],
         [325, 315,  21],
         [ 17, 325, 315],
         [  2,  17, 325],
         [318,   2,  17],
         [224, 318,   2],
         [  8, 224, 318],
         [ 21,   8, 224],
         [ 90,  21,   8],
         [484,  90,  21],
         [385, 484,  90],
         [ 17, 385, 484],
         [268,  17, 385],
         [202, 268,  17],
         [ 48, 202, 268],
         [106,  48, 202],
         [350, 106,  48],
         [ 44, 350, 106],
         [228,  44, 350],
         [  8, 228,  44],
         [ 21,   8, 228]]),
 tensor([313, 415,   4, 453, 217,   8,  21, 315, 325,  17,   2, 318, 224,   8,
          21,  90, 484, 385,  17, 268, 202,  48, 106, 350,  44, 228,   8,  21,
          37]))

## Create the MultiClass Model

In [45]:
class MultiClassClassification(nn.Module):

    def __init__(self,batch_size,embedding_dim,context_size,vocab_size):
        super().__init__()

        self.batch_size = batch_size
        self.embedding_dim = embedding_dim
        self.context_size = context_size

        # Create the embedding layer (1st layer) of the model
        self.embedding = nn.Embedding(vocab_size,embedding_dim) 

        # The 2nd layer of the model
        self.layer1 = nn.Linear(self.embedding_dim*self.context_size,128) 

        self.layer2 = nn.Linear(128,vocab_size)


    def forward(self,inputs):

        # pass the input through the embedding layer
        embed = self.embedding(inputs) # shape -> dimension (batch_size,vocab_size,embedding_dim)

        # Reshape the embed layers
        reshaped_embedd = embed.reshape(-1,self.embedding_dim*self.context_size)

        # pass the input through the first linear layer
        out = F.relu(self.layer1(reshaped_embedd))

        # pass the input through the final layer
        out = self.layer2(out)

        return out

In [46]:
batch_size = 32
embedding_dim = 64
context_size = 3
vocab_size = len(vocab)
model_0 = MultiClassClassification(batch_size,
                                  embedding_dim,
                                  context_size,
                                  vocab_size)

In [47]:
model_0

MultiClassClassification(
  (embedding): Embedding(490, 64)
  (layer1): Linear(in_features=192, out_features=128, bias=True)
  (layer2): Linear(in_features=128, out_features=490, bias=True)
)

In [50]:
## Check the model accountability

context,target = next(iter(dataloader))
context,target

(tensor([[ 21,   8,   6],
         [313,  21,   8],
         [415, 313,  21],
         [  4, 415, 313],
         [453,   4, 415],
         [217, 453,   4],
         [  8, 217, 453],
         [ 21,   8, 217],
         [315,  21,   8],
         [325, 315,  21],
         [ 17, 325, 315],
         [  2,  17, 325],
         [318,   2,  17],
         [224, 318,   2],
         [  8, 224, 318],
         [ 21,   8, 224],
         [ 90,  21,   8],
         [484,  90,  21],
         [385, 484,  90],
         [ 17, 385, 484],
         [268,  17, 385],
         [202, 268,  17],
         [ 48, 202, 268],
         [106,  48, 202],
         [350, 106,  48],
         [ 44, 350, 106],
         [228,  44, 350],
         [  8, 228,  44],
         [ 21,   8, 228]]),
 tensor([313, 415,   4, 453, 217,   8,  21, 315, 325,  17,   2, 318, 224,   8,
          21,  90, 484, 385,  17, 268, 202,  48, 106, 350,  44, 228,   8,  21,
          37]))

In [52]:
# predict the first batch with the model
model_0.eval()
with torch.inference_mode():
    out = model_0(context)
    print(out),print(out.shape)

tensor([[ 0.2081, -0.3166,  0.0926,  ...,  0.0053, -0.0523, -0.2014],
        [-0.0132,  0.1890, -0.1643,  ...,  0.1057,  0.3977, -0.3492],
        [ 0.0043, -0.4013, -0.2431,  ..., -0.2075, -0.0230, -0.4619],
        ...,
        [-0.0921,  0.0670, -0.0200,  ...,  0.0246,  0.3828, -0.0919],
        [-0.4510, -0.2042, -0.0503,  ..., -0.0269,  0.0721, -0.3608],
        [ 0.1562, -0.1658, -0.1161,  ...,  0.0397,  0.0515, -0.1111]])
torch.Size([29, 490])


In [54]:
# convert the logic into predict label
out = torch.argmax(out,dim =1)
out

tensor([158,   9, 294, 468, 313, 467, 381, 454, 417, 125, 321,  57, 134, 311,
        276, 375, 303, 172, 321, 100, 244, 388,  53, 172, 454, 209,   7,  25,
        454])

In [55]:
# index to word
index_word = vocab.get_itos()
index_word[32]

'knick-knack'

In [56]:
index_word[out[5].item()]

'turned'

In [57]:
for i in range(len(out)):
    print(index_word[out[i].item()])

don’t
on
w
umbrella
apple
turned
laugh
swimming
ring
hooray
bird
over
silver
american
s
its
“wah
merrily
bird
wash
horn
love
row
merrily
swimming
spider
go
man
swimming


In [75]:
def rhyme_generate(model,initial,tokens,num_of_words = 100):

    
    model.eval()


    index_to_word = vocab.get_itos()
    with torch.inference_mode():
        for i in range(CONTEXT_SIZE,num_of_words):
            context = torch.tensor(
                vocab([tokens[i-j-1] for j in range(CONTEXT_SIZE)])
            )

            word_idx = torch.argmax(model(context),dim = 1)
            

            initial += " " + index_to_word[word_idx.detach().item()]

    return initial
        
    

In [76]:
rhymes = rhyme_generate(model_0,'my rhyme',tokens)

In [77]:
rhymes

'my rhyme don’t on w umbrella apple turned laugh swimming ring hooray bird over silver american s its “wah merrily bird wash horn love row merrily swimming spider go man swimming over man bear row spider “wah dish cows spider bear horn turned merrily on hooray lock w ” went violin over macdonald nest reply reply turned don’t lock w down apple clothes its lock bone iceberg blue singing swimming bear its ears don’t should eating went lock reply nest merrily go lock w clothes man violin ears swimming cows lock x went should man put merrily cows bear'

In [78]:
def pickrandomline(rhyme):

    line = rhyme.split("\n")

    random_line = random.choice(line)

    return random_line
    

In [91]:
rand_line = pickrandomline(rhyme_collection)
rand_line

'And so the teacher turned it out,'

In [ ]:
## Pick a random line and then Create a rhyme
def create_rhyme_from_random_line(rhyme_collection):
    rand_line = pickrandomline

In [48]:
## Create the loss_function, optimizer, and scheduler

loss_fn = nn.CrossEntropyLoss()

optimizer = torch.optim.SGD(model_0.parameters(),
                           lr = 0.1)

scheduler = torch.optim.lr_scheduler.StepLR(optimizer,step_size = 1.0,gamma = 0.1)